services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - sportinj_db

  backend:
    image: ghcr.io/sportinj/backend:v1.0.0
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - sportinj_db
      - sportinj_bot

  bot:
    image: ghcr.io/sportinj/chatbot:v1.0.0
    env_file:
      - .env
    networks:
      - sportinj_bot

networks:
  sportinj_db:
  sportinj_bot:
